name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install project (pyproject-first)
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Smoke check
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import importlib; importlib.import_module('fitapp_core'); print('import ok')"
